// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC71afjM2dwxfmMiOzvqEg7rxiUUZzFHY',
    appId: '1:707720490987:web:8e2afef292e6e5526b33ae',
    messagingSenderId: '707720490987',
    projectId: 'cinema-bono',
    authDomain: 'cinema-bono.firebaseapp.com',
    storageBucket: 'cinema-bono.firebasestorage.app',
    measurementId: 'G-JVYWGW8E4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXE34dP1_7GDYYTJ61yEuzF1pOXAkpG6A',
    appId: '1:707720490987:android:37c97c290b7094056b33ae',
    messagingSenderId: '707720490987',
    projectId: 'cinema-bono',
    storageBucket: 'cinema-bono.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNg6xPIzL1GZGgIi2YPQFjvMGs-7f_eMM',
    appId: '1:707720490987:ios:42a5ef6fa26792476b33ae',
    messagingSenderId: '707720490987',
    projectId: 'cinema-bono',
    storageBucket: 'cinema-bono.firebasestorage.app',
    iosBundleId: 'com.example.cinemaBono',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNg6xPIzL1GZGgIi2YPQFjvMGs-7f_eMM',
    appId: '1:707720490987:ios:42a5ef6fa26792476b33ae',
    messagingSenderId: '707720490987',
    projectId: 'cinema-bono',
    storageBucket: 'cinema-bono.firebasestorage.app',
    iosBundleId: 'com.example.cinemaBono',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC71afjM2dwxfmMiOzvqEg7rxiUUZzFHY',
    appId: '1:707720490987:web:06dfcff310e0f6bd6b33ae',
    messagingSenderId: '707720490987',
    projectId: 'cinema-bono',
    authDomain: 'cinema-bono.firebaseapp.com',
    storageBucket: 'cinema-bono.firebasestorage.app',
    measurementId: 'G-2LCHDC47YV',
  );

}